services:
    news.command.fetchTitle:
        class: News\NewsBundle\Command\NewsFetchTitleCommand
        calls:
            - [setEventDispacher, ["@event_dispatcher"]]
        tags:
            -  { name: console.command }
    
    news.command.fetchLatest:
        class: News\NewsBundle\Command\NewsFetchLatestCommand
        calls:
            - [setEventDispacher, ["@event_dispatcher"]]
        tags:
            -  { name: console.command }

    news.fetch.title.subscriber:
        class: News\NewsBundle\EventListener\TitleFetchSubscriber
        arguments: ["@mailer", "%news_bundle_reposting_mail%"]
        tags:
            - {  name: kernel.event_subscriber }

    news.fetch.latest.subscriber:
        class: News\NewsBundle\EventListener\NewestFetchSubscriber
        arguments: ["@mailer", "%news_bundle_reposting_mail%"]
        tags:
            - {  name: kernel.event_subscriber }
            
    news.fetch.generic.subscriber:
        class: News\NewsBundle\EventListener\GenericFetchSubscriber
        arguments: ["@news.cache"]
        tags:
            - {  name: kernel.event_subscriber, priority: -255 }
            
    news.cache:
        class: Symfony\Component\Cache\Adapter\FilesystemAdapter
