services:
    news.command.fetchTitle:
        class: News\NewsBundle\Command\NewsFetchTitleCommand
        calls:
            - [setEventDispacher, ["@event_dispatcher"]]
        tags:
            -  { name: console.command }
    
    news.command.fetchLatest:
        class: News\NewsBundle\Command\NewsFetchLatestCommand
        calls:
            - [setEventDispacher, ["@event_dispatcher"]]
        tags:
            -  { name: console.command }

    news.fetch.title.subscriber:
        class: News\NewsBundle\EventListener\TitleFetchSubscriber
        tags:
            - {  name: kernel.event_subscriber }

    news.fetch.latest.subscriber:
        class: News\NewsBundle\EventListener\NewestFetchSubscriber
        tags:
            - {  name: kernel.event_subscriber }
